### ISSUE TITLE
revise code style

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr-validation-report#5]
Hey, 

we definitely need to unify the coding style + I think it might be better to make it more compact (fewer lines/whitespace) as long as it stays readable. 
Since we mix code and text quite liberally, I feel that the actual code can and should be as compact as possible - otherwise, it looks like a lot...

**Comment by max-pilz** [comment]
c.f. #7

**Comment by max-pilz** [comment]
@kkmann Could you give your feedback to the current version?

**Comment by kkmann** [comment]
better, but we can simplify things further I guess. started revision in #8
