### ISSUE TITLE
define global tolerances?

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr-validation-report#6]
should we define global tolerances for all tests or continue doing that loacally?

**Comment by max-pilz** [comment]
currently, for power and toer 1% relative deviation is allowed. We could defining this 1% at the beginning, but I think it is more clear in the current version.
Or do you mean sth different?

**Comment by kkmann** [comment]
nope exactly, I felt it would be better to define that in the index.Rmd, globally. Otherwise it is difficult to assess the overall quality of the validation

**Comment by max-pilz** [comment]
done in #10
